# Generated by Django 2.2.5 on 2022-10-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221001_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avatar',
            field=models.ImageField(blank=True, default='article/20220925/robot.png', upload_to='article/%Y%m%d/'),
        ),
    ]
